
# Language/versions
language: node_js
node_js:
  - "0.10"

# Services setup
services:
  - mongodb

# Build script
before_script:
  - npm install -g grunt-cli
  - cp config/test.sample.json config/test.json
  - grunt start-test &
  - sleep 5 # give server time to start
script: 'grunt ci'

# Notifications
notifications:
 email:
   - j.robinson@nature.com
   - perry.harlock@nature.com
   - rowan.manning@nature.com
