
# Language/versions
language: node_js
matrix:
  include:

    # Run tests in Node.js 0.10 (unsupported)
    - node_js: '0.10'

    # Run tests in Node.js 0.12
    - node_js: '0.12'

  # Allow Node.js 0.10 to fail â€“ it's unsupported
  allow_failures:
    - node_js: '0.10'

# Build only master (and pull-requests)
branches:
  only:
    - master

# Services setup
services:
  - mongodb

# Build script
before_script:
  - cp config/test.sample.json config/test.json
  - NODE_ENV=test node index.js &
  - sleep 5 # give server time to start
script: 'make ci'
